version: "3.9"

services:
  app:
    build:
      context: .
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: ["uv", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DB_USER:-notion}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-notion}
      POSTGRES_DB: ${DB_NAME:-notion_webhook}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
