name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v3
        with:
          python-version: '3.11'
          cache: true
          cache-dependency-path: |
            pyproject.toml
            uv.lock

      - name: Sync dependencies
        run: uv sync --extra dev --frozen

      - name: Run Ruff
        run: uv run ruff check .

  unit-tests:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v3
        with:
          python-version: '3.11'
          cache: true
          cache-dependency-path: |
            pyproject.toml
            uv.lock

      - name: Sync dependencies
        run: uv sync --extra dev --frozen

      - name: Run unit tests
        run: uv run pytest -q

  db-tests:
    runs-on: ubuntu-latest
    needs: [lint, unit-tests]
    services:
      postgres:
        image: postgres:16-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: notion
          POSTGRES_PASSWORD: notion
          POSTGRES_DB: notion_webhook
        options: >-
          --health-cmd "pg_isready -U notion" --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v3
        with:
          python-version: '3.11'
          cache: true
          cache-dependency-path: |
            pyproject.toml
            uv.lock

      - name: Sync dependencies
        run: uv sync --extra dev --extra postgres --frozen

      - name: Run tests with PostgreSQL
        env:
          DB_HOST: localhost
          DB_PORT: ${{ job.services.postgres.ports['5432'] }}
          DB_USER: notion
          DB_PASSWORD: notion
          DB_NAME: notion_webhook
          USE_POSTGRES: "1"
        run: uv run pytest -q
